### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Sakurann** [w3c/vc-status-list-2021#50] opened 2023-01-31 23:55 UTC
first question, what are we trying to version? I heard "objects", but would like to double click -  it is a claimset? what do we expect to change?

**Comment by mprorock** [comment] 2023-01-31 23:57
a possible alternate from #11 
```
{
  "@context": [
    "https://www.w3.org/credentials/v2",
    "https://w3id.org/vc/status-list/v2"
  ],
  "id": "https://example.com/credentials/status/3",
  "type": ["VerifiableCredential", "StatusListCredential"],
  "issuer": "did:example:12345",
  "issued": "2021-04-05T14:27:40Z",
  "credentialSubject": {
    "id": "https://example.com/status/3#list",
    "type": "StatusList",
    "ver": "2.0",
    "statusPurpose": "revocation",
    "encodedList": "H4sIAAAAAAAAA-3BMQEAAADCoPVPbQwfoAAAAAAAAAAAAAAAAAAAAIC3AYbSVKsAQAAA"
  },
  "proof": { ... }
}
```

**Comment by msporny** [comment] 2023-02-01 14:59
> first question, what are we trying to version? I heard "objects", but would like to double click - it is a claimset? what do we expect to change?

It's not a claimset.

We're trying to version specific instances of classes (in the OOP sense of the word). Some people call these things "objects", others call them "instances of classes". For status list, in particular, we need to version two things... the status list entry (an object which appears in the VC), and the status list credential itself (an object which is a separate VC, but appears elsewhere on the Internet). This is how we version the status list entry today:

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/vc/status-list/2021/v1"
  ],
  "type": ["VerifiableCredential"],
  ...
  "credentialStatus": {
    "id": "https://example.com/credentials/status/3#94567"
    "type": "StatusList2021Entry", <--- specifically, this line is the version of the status list entry
    "statusPurpose": "revocation",
    "statusListIndex": "94567",
    "statusListCredential": "https://example.com/credentials/status/3"
  },
  ...
}
```

and this is how we version the status list credential: 

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/vc/status-list/2021/v1"
  ],
  ...
  "type": ["VerifiableCredential", "StatusList2021Credential"], <-- specifically, this line
  ...
  "credentialSubject": {
    "id": "https://example.com/status/3#list",
    "type": "StatusList2021", <--- and this line
    "statusPurpose": "revocation",
    "encodedList": "H4sIAAAAA...AQAAA"
  },
  ...
}
```

We do specific versioning because the properties in the next version for StatusList2021Entry, StatusList2021Credential, and StatusList2021 could change in ways that could be breaking changes. If we plan ahead, and version now, we don't have to worry about breaking changes in the future.

If we remove versioning and just use class names like `StatusList`, we can no longer make breaking changes... or if we do breaking changes, needing compatability code for every version of software that ships that uses `StatusList` (without the version). IOW, we guarantee code bloat over the next decade or so and we guarantee failures for older software reading `StatusList` that contains newer features. That's why we aggressively version everything in the VC ecosystem, because our experience over the past several years has demonstrated that we regularly make breaking changes to subparts of a VC (the cryptosuites being the best example of this, but the previous status list format being another example... where the bitstring format was different).

Hope that helps explain /why/ we version... I'll post a bit later on the benefits/drawbacks of semantic versioning vs. date-based versioning when I have a break in my calls today.

**Comment by msporny** [comment] 2023-02-11 19:45
Somewhat of a duplicate of this issue: https://github.com/w3c/vc-data-integrity/issues/38

**Comment by OR13** [comment] 2023-06-08 03:12
Can we close this?

These terms are now shipped in the core context.

**Comment by msporny** [comment] 2023-09-14 20:29
We have removed versions from the names, closing.

**Closed by msporny** 2023-09-14 20:29 UTC
Labels: before-CR
